# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"make_df": "sklearn-lda.ipynb",
         "chinese_word_cut": "sklearn-lda.ipynb",
         "print_top_words": "sklearn-lda.ipynb",
         "get_custom_stopwords": "sklearn-lda.ipynb",
         "lda_on_chinese_articles_with_param": "sklearn-lda.ipynb",
         "lda_on_chinese_articles": "sklearn-lda.ipynb"}

modules = ["sklearn_lda.py"]

doc_url = "https://JiaxiangBU.github.io/dynamic_topic_modeling/"

git_url = "https://github.com/fastai/dynamic_topic_modeling/tree/master/"

def custom_doc_links(name): return None
